financeproduct/bank/urls.py
from django.urls import path
from . import views

app_name = 'bank'
urlpatterns = [
    path('', views.searchbank, name='searchbank'),
]

financeproduct/exchange/urls.py
from django.urls import path
from . import views

app_name = 'exchange'
urlpatterns = [
    path('', views.exchange, name='exchange'),
    path('calculate/', views.calculate_exchange_rate, name='calculate'),
]

financeproduct/financeproduct/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('boards/', include('boards.urls')),
    path('accounts/', include('dj_rest_auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/signup/', include('dj_rest_auth.registration.urls')),
    path('bank/', include('bank.urls')),
    path('exchange/', include('exchange.urls')),
    path('products/', include('products.urls')),
]

financeproduct/exchange/models.py
from django.db import models

# Create your models here.

financeproduct/exchange/views.py
from django.shortcuts import render
from django.conf import settings
import requests
from datetime import datetime
# Create your views here.

def exchange(request):
    return render(request, 'exchange/exchange.html')

def calculate_exchange_rate(request):
    amount = float(request.GET.get('amount'))
    from_currency = request.GET.get('from_currency')
    to_currency = request.GET.get('to_currency')
    
    api_key = settings.EXCHANGE_API_KEY  # 한국수출입은행 API 키
    
    current_date = datetime.now()
    current_date = current_date.strftime("%Y%m%d")
    api_url = f"https://www.koreaexim.go.kr/site/program/financial/exchangeJSON?authkey={api_key}&searchdate={current_date}&data=AP01"

    response = requests.get(api_url)
    data = response.json()
    print(data)
    exchange_rate = None
    for item in data:
        if item['cur_unit'] == from_currency:
            rate1 = item['deal_bas_r']
            rate1 = rate1.replace(',', '')
            rate1 = float(rate1)
        if item['cur_unit'] == to_currency:
            rate2 = item['deal_bas_r']
            rate2 = rate2.replace(',', '')
            rate2 = float(rate2)
    exchange_rate = rate1 / rate2
    
    if exchange_rate is not None:
        result = amount * float(exchange_rate)
        result = round(result, 2)
        result_message = f"{amount} {from_currency} = {result} {to_currency}"
    else:
        result_message = "환율 정보를 가져올 수 없습니다."
        
    return render(request, 'exchange/exchange.html', {'result_message': result_message})

financeproduct/exchange/templates/exchange/exchange.html
{% extends 'base.html' %}

{% block content %}
<h1>환율 계산</h1>

<form method="GET" action="{% url 'exchange:calculate' %}">
    <label for="amount">액수:</label>
    <input type="number" id="amount" name="amount" min="0" required>
    <br>
    <label for="from_currency">원래 통화:</label>
    <select id="from_currency" name="from_currency" required>
        <option value="USD">USD</option>
        <option value="EUR">EUR</option>
        <option value="JPY(100)">JPY</option>
        <option value="KRW">KRW</option>
        <!-- 다른 통화 코드도 추가하세요 -->
    </select>
    <br>
    <label for="to_currency">변환할 통화:</label>
    <select id="to_currency" name="to_currency" required>
        <option value="USD">USD</option>
        <option value="EUR">EUR</option>
        <option value="JPY(100)">JPY</option>
        <option value="KRW">KRW</option>
        <!-- 다른 통화 코드도 추가하세요 -->
    </select>
    <br>
    <button type="submit">환율 계산</button>
</form>

{% if result_message %}
    <div id="result">{{ result_message }}</div>
{% endif %}

{% endblock content %}