financeproduct/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/<username>/', views.profile, name='profile'),
    path('<int:user_pk>/follow/', views.follow, name='follow'),
    
    # path('google/login', views.google_login, name='google_login'),
    # path('google/callback/', views.google_callback, name='google_callback'),  
    # path('google/login/finish/', views.GoogleLogin.as_view(), name='google_login_todjango'),
]

financeproduct/bank/urls.py
from django.urls import path
from . import views

app_name = 'bank'
urlpatterns = [
    path('', views.searchbank, name='searchbank'),
]

financeproduct/boards/urls.py
from django.urls import path
from . import views

app_name="boards"
urlpatterns = [
    path('', views.index, name="index"),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'), 
    path('<int:pk>/update/', views.update, name='update'),   
    path('<int:board_pk>/comment/', views.comment, name='comment'),
    path('<int:board_pk>/comment/<int:comment_pk>/', views.comment_detail, name='comment_detail'),
    path('<int:board_pk>/likes/', views.likes, name='likes'),
]

financeproduct/exchange/urls.py
from django.urls import path
from . import views

app_name = 'exchange'
urlpatterns = [
    path('', views.exchange, name='exchange'),
    path('calculate/', views.calculate_exchange_rate, name='calculate'),
]

financeproduct/financeproduct/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('boards/', include('boards.urls')),
    path('accounts/', include('dj_rest_auth.urls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/signup/', include('dj_rest_auth.registration.urls')),
    path('bank/', include('bank.urls')),
    path('exchange/', include('exchange.urls')),
    path('products/', include('products.urls')),
]

financeproduct/home/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('home/', views.home, name='home'),
]

financeproduct/templates/_navbar.html
<nav class="navbar navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home:home' %}">Finance Products</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasDarkNavbar" aria-controls="offcanvasDarkNavbar" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
</button>
<div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasDarkNavbar" aria-labelledby="offcanvasDarkNavbarLabel">
    <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasDarkNavbarLabel">
            {% if user.is_authenticated %}
            {{user.username}}
            <br>
            <a href="{% url 'accounts:profile' user.username %} ">내 프로필</a>
            <a href="{% url 'accounts:logout' %}">로그아웃</a>
            {% else %}
            <a href="{% url 'accounts:login' %}">로그인</a>
            <a href="{% url 'accounts:signup' %}">회원가입</a>
            {% endif %}</h5>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
        <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">홈</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'boards:index' %}">금융 상품</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'exchange:exchange' %}">환율 계산기</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'bank:searchbank' %}">주변 은행 찾기</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'boards:index' %}">자유게시판</a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown
            </a>
            <ul class="dropdown-menu dropdown-menu-dark">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li>
                    <hr class="dropdown-divider">
                </li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
        </li>
    </ul>
    <form class="d-flex mt-3" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-success" type="submit">Search</button>
    </form>
</div>
    </div>
</div>
</nav>

financeproduct/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  <title>Document</title>
  <style>
    body {
      padding-top: 60px;
    }
  </style>
</head>
<body>
  <div class="mt-3 mb-4">
    {% include '_navbar.html' %}
  </div>
  <div class="mb-5">
    {% block content %}
    {% endblock content %}
  </div>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
</body>
</html>